// ─── Taste schemas (shared by REST routes + MCP tools) ───
//
// This file is the SINGLE SOURCE OF TRUTH for Taste input/output shape.
// Both `backend/src/routes/tasteRoutes.ts` and `backend/mcp-server/src/tools/tasteTools.ts`
// import from here — see CLAUDE.md "MCP Server 与 REST API 的同步规则".

import { z } from "zod";

// ─── Meta (设计风格结构化元数据) ───
//
// Generated by `tasteMetaService.ts` from each Taste's SVG content.
// Consumed by the Chat Agent via `get_taste(includeMeta:true)`.
// Not rendered in the FE in Phase 1 (per user decision 2026-04-22).

export const tasteMetaSchema = z
  .object({
    themeColor: z.string().optional(),      // 主色调, hex #aabbcc
    hoverColor: z.string().optional(),      // hover 色
    auxColors: z.array(z.string()).max(5).optional(), // 辅助色，最多 5 个
    fontFamily: z.string().optional(),      // 字体族
    fontSize: z.number().optional(),        // 主文本字号 (px, 无单位)
    lineHeight: z.union([z.number(), z.string()]).optional(), // 行高
    padding: z.string().optional(),         // CSS padding, e.g. "12px 16px"
    gap: z.union([z.number(), z.string()]).optional(),
    borderRadius: z.union([z.number(), z.string()]).optional(),
    boxWidth: z.number().optional(),
    boxHeight: z.number().optional(),
    shadow: z.string().optional(),          // CSS box-shadow
    tags: z.array(z.string()).optional(),   // button / card / modal / input / navbar ...
    description: z.string().max(80).optional(), // ≤40 字一句话概括
  })
  .strict();

export type TasteMeta = z.infer<typeof tasteMetaSchema>;

// Meta 响应（GET /meta）
export const tasteMetaResponseSchema = z.object({
  meta: tasteMetaSchema.nullable(),
  generatedAt: z.string().datetime().nullable(),
  status: z.enum(["ready", "generating", "failed", "missing"]),
});

export type TasteMetaResponse = z.infer<typeof tasteMetaResponseSchema>;

// ─── Create from SVG (MCP & REST) ───

export const createTasteFromSvgSchema = z.object({
  designId: z.string().min(1),
  svg: z.string().min(1).max(5 * 1024 * 1024), // 5MB cap (matches existing /from-svg)
  name: z.string().min(1).max(200).optional(),
});

export type CreateTasteFromSvgInput = z.infer<typeof createTasteFromSvgSchema>;

// ─── Update (position / size / name — no content) ───

export const updateTasteSchema = z.object({
  name: z.string().min(1).max(200).optional(),
  x: z.number().finite().optional(),
  y: z.number().finite().optional(),
  width: z.number().positive().finite().optional(),
  height: z.number().positive().finite().optional(),
  order: z.number().int().optional(),
});

export type UpdateTasteInput = z.infer<typeof updateTasteSchema>;

// Batch update
export const batchUpdateTastesSchema = z.object({
  designId: z.string().min(1),
  updates: z
    .array(
      z.object({
        id: z.string().min(1),
        x: z.number().finite().optional(),
        y: z.number().finite().optional(),
        width: z.number().positive().finite().optional(),
        height: z.number().positive().finite().optional(),
      }),
    )
    .min(1)
    .max(500),
});

export type BatchUpdateTastesInput = z.infer<typeof batchUpdateTastesSchema>;

// ─── Summary (returned by list_tastes — no SVG content to save tokens) ───

export const tasteSummarySchema = z.object({
  id: z.string(),
  designId: z.string(),
  name: z.string(),
  x: z.number(),
  y: z.number(),
  width: z.number(),
  height: z.number(),
  source: z.string(),
  hasMeta: z.boolean(), // Agent 可据此决定是否需要调 get_taste(includeMeta:true)
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export type TasteSummary = z.infer<typeof tasteSummarySchema>;

// ─── Detailed (returned by get_taste) ───

export const tasteDetailSchema = tasteSummarySchema.extend({
  fileName: z.string(),
  filePath: z.string().nullable(),
  figmaUrl: z.string().nullable(),
  svg: z.string().optional(),        // only when includeSvg=true
  meta: tasteMetaSchema.nullable().optional(), // only when includeMeta=true
  metaGeneratedAt: z.string().datetime().nullable().optional(),
});

export type TasteDetail = z.infer<typeof tasteDetailSchema>;
